### ISSUE TITLE
Can not start qt-amdgpu-fan-ctl.py with error: No module named 'pyqtgraph'

### ISSUE THREAD

**Issue by shados250** [wepiha/qt-amdgpu-fan-ctl#5]
Hello!

When i am starting "qt-amdgpu-fan-ctl.py", this error happens: No module named "pyqtgraph"
![Error_Screenshot](https://user-images.githubusercontent.com/50293102/210384439-d9686e6b-2b80-4b06-b049-e164f3f9927d.png)
All dependent libraries in place:
![Python_libs_Screenshot](https://user-images.githubusercontent.com/50293102/210384445-75945d3e-931d-4053-a698-ba9d4bb9a529.png)

The downloaded branch: Master.
OS: Kernel: 6.0.0-6-amd64 arch: x86_64 bits: 64 Console: pty pts/2
    Distro: Debian GNU/Linux bookworm/sid
Python version: Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

Are any solves ?

**Comment by wepiha** [comment]
Hey

Sorry this has not had maintenance for some time, however; if goy want to
try the following it may help:

pip install pyqtgraph


It may work.

- wepih

**Comment by shados250** [comment]
Yeah, installing via pip3 helped me:

`sudo pip3 install pyqtgraph`

Thank you.
